name: Deploy documentation web

on:
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v4
            # We can't use https://github.com/withastro/action as it install dependencies
            # at root directory, not the defined sub path
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Enable Corepack
              run: corepack enable

            - name: Install Corepack
              run: corepack install

            - name: Install
              run: yarn install --immutable

            - name: Build
              working-directory: ./docs/web
              run: yarn build

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './docs/web/dist/'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
