name: Deploy

on:
  push:
    tags:
      - "ext-*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: ./vscode-extension

      - name: Deploy to marketplace
        run: yarn deploy
        working-directory: ./vscode-extension
        env:
          VSCE_PATH: ${{ secrets.VSCODE_SECRET }}
