name: Deploy extension

on:
  push:
    tags:
      - "ext-*"

jobs:
  publish-marketplace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: ./vscode-extension

      - name: Deploy to marketplace
        run: yarn deploy
        working-directory: ./vscode-extension
        env:
          VSCE_PAT: ${{ secrets.VSCODE_SECRET }}
